### ISSUE TITLE
Charge Point page issue

### ISSUE THREAD

**Issue by stbungaof** [MuhammedAlmaz/ma-ocpp-simulator#11]
![image](https://github.com/MuhammedAlmaz/ma-ocpp-simulator/assets/7788423/3d3e67a1-e69f-43bf-9a18-3e2e59240e73)

![image](https://github.com/MuhammedAlmaz/ma-ocpp-simulator/assets/7788423/920fea6b-d0d0-4068-be04-a7c848fbeb51)

**Comment by MuhammedAlmaz** [comment]
It fixed https://github.com/MuhammedAlmaz/ma-ocpp-simulator/pull/14 can you pull repository and check again please?

**Comment by stbungaof** [comment]
Work fine. Thank bro.
