### ISSUE TITLE
Not able to access core functionalities after starting the application, can you please help?

### ISSUE THREAD

**Issue by sc-aniagr** [MuhammedAlmaz/ma-ocpp-simulator#12]
![image](https://github.com/MuhammedAlmaz/ma-ocpp-simulator/assets/108719736/5c59fb67-0d86-4ecd-a449-356bed93749d)

**Comment by MuhammedAlmaz** [comment]
Same with https://github.com/MuhammedAlmaz/ma-ocpp-simulator/issues/11.

**Comment by sc-aniagr** [comment]
![image](https://github.com/MuhammedAlmaz/ma-ocpp-simulator/assets/108719736/22954d00-d071-4c53-896f-a6c381c16885)


tried taking pull and rebuilding the component. didnt help much, stiill stuck with the same. can you please help?

**Comment by MuhammedAlmaz** [comment]
@sc-aniagr Did you see anything on your console? Can you share with me your console please? I've tried a lot time but didn't see any bug.
