### ISSUE TITLE
branch name change not reflected in instructions

### ISSUE THREAD

**Issue by makusets** [MuhammedAlmaz/ma-ocpp-simulator#33]
Dear Muhammed,

By the looks of it, you changed the rep name from ma-charge-point-simulator to ma-ocpp-simulator. The instructions have not been updated and the suggested git and docker commands don't work. Took me a while to figure out.

Thanks for your contribution.

**Comment by MuhammedAlmaz** [comment]
I'll change same name now thanks for report.
