### ISSUE TITLE
[config] Struggling to test StartTransaction

### ISSUE THREAD

**Issue by rafaelcf03** [MuhammedAlmaz/ma-ocpp-simulator#6]
Hey! I can't test StartTransaction and simulate a charging scenario. Connector keeps on "Preparing" status. Perhaps I missed something. Am I doing something wrong or is it bug?

![Captura de tela de 2024-04-25 10-05-01](https://github.com/MuhammedAlmaz/ma-ocpp-simulator/assets/29259776/4443ac49-8453-4527-b465-bcc85e26f50d)
![Captura de tela de 2024-04-25 10-05-07](https://github.com/MuhammedAlmaz/ma-ocpp-simulator/assets/29259776/ac3aa5c3-d470-476b-8f01-d254064c24cd)

Thank you!

**Comment by MuhammedAlmaz** [comment]
Hello @rafaelcf03 Can you show your logs please? You cannot start transaction directly you need idTag variable for start transaction so you should use RemoteStartTransaction from back-end service. But I will add startTransaction with idTag feature in couple hours.

**Comment by rafaelcf03** [comment]
Oooh I see. I'll try that. Didn't realize. 
Can't wait to test startTransaction feature! Thank you so much!

**Comment by MuhammedAlmaz** [comment]
@rafaelcf03 it is already ready on this PR https://github.com/MuhammedAlmaz/ma-ocpp-simulator/commit/f8302553c7c404e5b0bd37f66beb45dfdfefa85a . Here you go good work :)
